compute_environment: LOCAL_MACHINE
debug: false
deepspeed_config:
  zero_optimization:
    stage: 2
    allgather_partitions: true
    allgather_bucket_size: 200000000
    overlap_comm: true
    reduce_scatter: true
    reduce_bucket_size: 200000000
    contiguous_gradients: true
    cpu_offload: false
  bf16:
    enabled: true
  gradient_accumulation_steps: 4
  train_micro_batch_size_per_gpu: 12
  gradient_clipping: 1.0
  steps_per_print: 2000
  wall_clock_breakdown: false
distributed_type: DEEPSPEED
downcast_bf16: false
enable_cpu_affinity: false
machine_rank: 0
main_training_function: main
mixed_precision: bf16
num_machines: 1
num_processes: 2
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false